# Flutter B2B Template - Analysis Options (2025)
# Balanced configuration: Strict where it matters, flexible where it helps

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - "build/**"

  # Strict mode for type safety
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    # Critical errors
    missing_required_param: error
    missing_return: error
    invalid_annotation_target: error

    # Allow TODOs in development
    todo: ignore

    # Warnings for important issues
    unawaited_futures: warning
    discarded_futures: warning

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # ==========================================
    # CRITICAL: Error Prevention (Must Have)
    # ==========================================
    unawaited_futures: true
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    close_sinks: true
    discarded_futures: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unsafe_html: true

    # ==========================================
    # Code Style & Consistency
    # ==========================================
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_constructors_first: true
    directives_ordering: true

    # ==========================================
    # Null Safety
    # ==========================================
    avoid_null_checks_in_equality_operators: true
    avoid_returning_null_for_future: true
    prefer_if_null_operators: true
    unnecessary_null_checks: true

    # ==========================================
    # Widget Best Practices
    # ==========================================
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true
    use_full_hex_values_for_flutter_colors: true
    use_colored_box: true
    use_decorated_box: true

    # ==========================================
    # Performance
    # ==========================================
    avoid_function_literals_in_foreach_calls: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_inlined_adds: true

    # ==========================================
    # Security (B2B Critical)
    # ==========================================
    avoid_web_libraries_in_flutter: true
    secure_pubspec_urls: true

    # ==========================================
    # Immutability
    # ==========================================
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true

    # ==========================================
    # Code Quality
    # ==========================================
    avoid_bool_literals_in_conditional_expressions: true
    avoid_annotating_with_dynamic: true
    no_leading_underscores_for_local_identifiers: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    unnecessary_parenthesis: true
    unnecessary_this: true

# Riverpod custom lints
custom_lint:
  enable_all_lint_rules: true
